# Generated by Django 5.0.6 on 2024-08-19 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_livro_autores"),
        ("uploader", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="livro",
            name="autores",
        ),
        migrations.RemoveField(
            model_name="livro",
            name="categoria",
        ),
        migrations.RemoveField(
            model_name="livro",
            name="editora",
        ),
        migrations.RemoveField(
            model_name="livro",
            name="isbn",
        ),
        migrations.RemoveField(
            model_name="livro",
            name="preco",
        ),
        migrations.RemoveField(
            model_name="livro",
            name="quantidade",
        ),
        migrations.RemoveField(
            model_name="livro",
            name="titulo",
        ),
        migrations.AddField(
            model_name="livro",
            name="capa",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="uploader.image",
            ),
        ),
    ]
