# Generated by Django 5.0.6 on 2024-08-20 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_livro_autores_livro_categoria_livro_editora_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="autor",
            name="site",
        ),
        migrations.AddField(
            model_name="autor",
            name="email",
            field=models.URLField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="autor",
            name="nome",
            field=models.CharField(default="...", max_length=100),
        ),
    ]
