# Generated by Django 5.0.6 on 2024-08-23 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_remove_autor_site_autor_email_alter_autor_nome"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autor",
            name="nome",
            field=models.CharField(default="", max_length=100),
        ),
    ]
