# Generated by Django 5.0.6 on 2024-09-10 17:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_user_foto_alter_user_passage_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="passage_id",
            field=models.CharField(
                default=uuid.UUID("03ba29e6-6a77-4c84-a453-69d82f26567b"),
                help_text="Passage ID",
                max_length=255,
                unique=True,
                verbose_name="passage_id",
            ),
        ),
    ]
