# Generated by Django 5.0.6 on 2024-09-13 17:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_alter_user_passage_id_itenscompra"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="passage_id",
            field=models.CharField(
                default=uuid.UUID("c3cda30b-0d72-4547-ab2e-b0ab478d2fd6"),
                help_text="Passage ID",
                max_length=255,
                unique=True,
                verbose_name="passage_id",
            ),
        ),
        migrations.DeleteModel(
            name="ItensCompra",
        ),
    ]
