# Generated by Django 5.0.6 on 2024-09-13 17:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_alter_user_passage_id_itenscompra"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="passage_id",
            field=models.CharField(
                default=uuid.UUID("73ea31a5-caba-4aeb-acfd-7fbea69c77eb"),
                help_text="Passage ID",
                max_length=255,
                unique=True,
                verbose_name="passage_id",
            ),
        ),
    ]
